### ISSUE TITLE
Fix bad rows in KCOR_QUALITY

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#113]
Find and fix the bad horizontal lines in the raw images in quality, L1 processing, and calibration.

The bad lines are reported in:

    /hao/twilight/Data/KCor/logs.script

Appropriate thresholds for how many times a bad line is detected need to be created.

#### Tasks

- [x] find and fix bad lines in `kcor_quality` (reporting back to `kcor_l1`)
- [x] fix bad lines in `kcor_l1`
- [x] find and fix bad lines in `kcor_reduce_calibration_read`
- [x] remove `horizontal_artifact_lines` and `horizontal_artifact_cameras` from `epochs.cfg` and `epochs.spec.cfg`

**Comment by mgalloy** [comment]
This is in production as of version [1.6.15].

[1.6.15]: https://github.com/NCAR/kcor-pipeline/releases/tag/v1.6.15
