### ISSUE TITLE
Create and use calibration file from 20131101 for cal epoch version 2

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#121]
In epoch 2 the `SKYTRANS` correction is computed from a fit to the Nov 1, 2013 SGS data. We need to calibrate the images in that epoch with a cal file from the same date (11/1/13) since the sky transmission is normalized to the gain, i.e. the flat.

#### Tasks

- [x] mark as do not process for calibration data on 20131101 that is not from 19:18:31 to 19:30:39
- [x] create a cal file from data on 20131101 *using only data* from 19:18:31 to 19:30:39
- [x] replace the current 'hardwired' cal file from 20131016  with the new file from 20131101
- [x] One last step: Have Mike edit the epochs.cfg file to NOT produce a calibration on Oct 16. We want to use the Nov 1 calibration file to correspond to the Nov 1 sky transmission correction that is used in this epoch of the processing (Epoch 2: Oct 4 18:36 to Nov 11 18:15.

**Comment by jburkepile** [comment]
**The final step** is to compare the quality of the K-Cor data processed with the Nov 1 calibration with the good quality calibration from Oct 16.  Mike reprocessed Nov 1, 2013 data with both the Oct 16 and Nov 1 calibrations.  Comparisons between the two calibration files show:  1) the Nov 1, 2013 calibration file is of good quality; 2) The difference between the  level 2 intensities processed with the 2 different calibrations is very small; showing consistency of the calibrations.  I've attached azimuthal scans at a few different heights comparing the results from the 2 calibrations. I selected two images: one early in the observing day and one late in the day since sky transmission effects are greatest at these times. The first two plots below are at different heights in the corona for the early image and the bottom two plots are for different heights for the later image.  
![20131101_181548_kcor_l2_cal20131101_r1 20_plot](https://user-images.githubusercontent.com/18175973/110696495-68f04e00-81a8-11eb-8c80-ab1ef50421d7.gif)
![20131101_181548_kcor_l2_cal20131101_r1 60_plot](https://user-images.githubusercontent.com/18175973/110696519-6d1c6b80-81a8-11eb-8c55-0c7d01773a2c.gif)

Later in day:
![20131102_021155_kcor_l2_cal20131101_r1 15_plot](https://user-images.githubusercontent.com/18175973/110696551-7574a680-81a8-11eb-9293-8c7926442fe9.gif)
![20131102_021155_kcor_l2_cal20131101_r1 60_plot](https://user-images.githubusercontent.com/18175973/110696563-786f9700-81a8-11eb-9710-f43c1f43cc97.gif)
