### ISSUE TITLE
Add subtraction images and movie to web archive and database

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#235]
In end-of-day pipeline:

- [x] copy "good" and "pass" subtraction FITS, GIFs, and mp4 to appropriate web archive directories
- [x] tar up all subtraction images with level 2 data in tarball that gets shipped to campaign storage
- [x] add "good" and "pass" subtraction image entries to database

#### Questions

- [x] Currently, all difference GIF and FITS files are copied to the web archive directories. Should it only be "good" and "pass"? *Yes*

#### Tasks

- [x] only distribute "good" and "pass" to web archive

**Comment by mgalloy** [comment]
Needed a new pB difference product type for difference images in the database:

``` SQL
insert into mlso_producttype (producttype, description) values ('pBdiff', 'K-Cor pB difference image');
```
