### ISSUE TITLE
Process 2019 data with different NUMSUM values

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#282]
- [x] 20190612  09:21:30 [HST]   **Don't process** These are calibration data with numsum = 512. Another calib set was acquired this day with numsum = 171. Only use the numsum = 171 for this day.
- [x] 20190612  09:34:08 [HST]  Resume nominal processing. No special requirements.
- [x] 20190612  EPOCH: 12:16:14  [HST]  **numsum = 171** Epoch contains science images **and a calibration sequence that can be used to process data taken between June 12 and July 2 with numsum = 171**.
- [x] 20190612 EPOCH: 12:52:55  [HST] numsum = 512 again. Resume nominal processing. 
- [x] Create new calibration file with a new calib. version number for 20190612 using only cal files with numum = 171
- [x] 20190618 EPOCH 10:09:41  [HST]  numsum = 171. Need to use calibration file from 20190612 (same calibration version with numsum = 171)
- [x] 20190619 EPOCH:  06:31:12  [HST]  numsum = 512   Resume nominal processing. 
- [x] 20190702 EPOCH:  06:57:59 [HST]  numsum = 171. Need to use calibration file from 20190612 (same calibration version with numsum = 171)
- [x] 20190703 EPOCH:  07:00:07 [HST]  numsum = 512. Resume nominal processing.

**One more fix for 2019 that does NOT involve NUMSUM:**

- [x] 20190311 EPOCH: 08:20:10 [HST]  Don't process. These are calib. images and clouds rolled in during the calib. sequence. A second calibration sequence was taken later in the day.
- [x] 20190311 EPOCH:  08:33:03 [HST]   Resume nominal processing.
- [x] Recreate calibration file for 20190311. The first set of 'cloudy' calib. images will be excluded and only the second set will be used.

#### Tasks

Reprocess the following days to test (results in `raw.numsum`):

- [x] 20190311
- [x] 20190612
- [x] 20190618
- [x] 20190619
- [x] 20190702
- [x] 20190703

**Comment by mgalloy** [comment]
91def8c25598d27ccbb8af715c9477203f6a6d55 adds the epochs noted above.

**Comment by mgalloy** [comment]
Testing this requires processing 20190612, 20190618, 20190619, 20190702, 20190703, and 20190311.

**Comment by jburkepile** [comment]
Examined June 12, 2019 pB over the day and it looks stable. That includes images close together in  time that had different numsum values (i.e. 171, 512) and the pB signals were comparable.
