### ISSUE TITLE
Create epochs to avoid using bad cal files with wrong polarizer angle(s) 

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#336]
Need to avoid using a number of calibration files that contain at least a few calibration polarizer images taken with the polarizer at the wrong angle: the polarizer was at 23.9 degrees instead of zero or 180 degrees. 23.9 degrees is NOT a invalid angle and will corrupt the integrity of the calibration. Need to:
1) create epochs to avoid using bad cal files
2) reprocess days impacted by bad cal files

**Create epochs:**
- [x] 20140102 09:02:00 [HST]  DO NOT PROCESS.  Bad calpol angle
- [x] 20140102 09:14:23 [HST] Begin processing good data
- [x] 20140224 09:33:29  [HST]  DO NOT PROCESS.  Bad calpol angle
- [x] 20140224 09:45:52 [HST] Begin processing good data
- [x] 20140509 10:35:31 [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20140509 10:47:55 [HST] Begin processing good data
- [x] 20140523 07:53:42 [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20140523 08:06:05 [HST] Begin processing good data
- [x] 20141115 09:28:41  [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20141115 09:40:49  [HST] Begin processing good data
- [x] 20141208 10:56:23 [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20141208 11:08:47 [HST] Begin processing good data
- [x] 20141219 09:10:34 [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20141219 09:22:58 [HST] Begin processing good data
- [x] 20141229 09:10:05 [HST] DO NOT PROCESS.  Bad calpol angle
- [x] 20141229 09:22:44 [HST] Begin processing good data

NEXT: Reprocess days impacted by bad cal files:

- [x] 20140102
- [x] 20140224
- [x] 20140509
- [x] 20140522
- [x] 20140523
- [x] 20141115
- [x] 20141208
- [x] 20141219
- [x] 20141229
- [x] 20141206 - bad calibration polarizer angle 23.8 deg  [days above this had angle of 23.9 deg]
- [x] 20141210 - bad calibration polarizer angle 23.8 deg
- [x] 20141211 - bad calibration polarizer angle 23.8 deg
- [x] 20141215 - bad calibration polarizer angle 23.8 deg
- [x] 20141226 - bad calibration polarizer angle 23.8 deg
- [x] 20141230 - bad calibration polarizer angle 23.8 deg
- [x] 20141231 - No cal file this day. 12/30 calibration was used for beginning of this day. Need to reprocess with good file

#### Tasks

- [x] update `kcor_check_angles` to return a mask array, instead of a single binary value, to check the files with dark=out, diff=in, calpol=in:
  1. must have all `required_angles = [0.0, 45.0, 90.0, 135.0]` degrees
  2. can have `required_angles + 22.5`
  3. throw out any observations (files) where the angle is not `required_angles` or `required_angles + 22.5`
- [x] verify files/types in cal file metadata vs logs of calibration processing vs `calibration_files.txt` in `process` to make sure that the right files are eliminated
- [x] verify full processing of above test dates is good

#### Summary

The pipeline now handles cal pol files with non-nominal angles — removing the observations with bad angles, but processing the rest of the cal data unless all the required angles are not present.

We verified that the changes made to remove the 'bad' angles from the calibration files was successful. The 'evil twin' CME on Dec 20 2014 (see 00:48 image further down in this ticket) was removed in the reprocessed data. We also examined the stability of the calibrated pB images (see pB plots from Dec 31, 2014 further down in this ticket). The pB calibration was much more stable over the day when the 'bad' calibration angles were removed.

**Comment by mgalloy** [comment]
Actually, there are many, many days with bad cal files with odd cal angles. These days must automatically catch the bad days. For some reason `kcor_check_angles` is not finding those days.

**Comment by mgalloy** [comment]
OK, `kcor_check_angles` checks to make sure every required angle is present in the calibration polarization angles, but not if there are extra angles present. Will check both ways.

**Comment by mgalloy** [comment]
Reprocessing the mission #346 will address this issue. Closing.

**Comment by mgalloy** [comment]
I reprocessed 20140102 in `raw.latest` to test this. I changed the `epochs.cfg` file for the test to process all the files for the day, not manually removing the bad files. In the log, I got:

```
2024-04-23 15:38:02 DEBUG: KCOR_CHECK_ANGLES: cal angle 23.85 not required or optional, removing...
2024-04-23 15:38:02 DEBUG: KCOR_CHECK_ANGLES: cal angle 23.85 not required or optional, removing...
2024-04-23 15:38:02 DEBUG: KCOR_CHECK_ANGLES: cal angle 23.85 not required or optional, removing...
```

**Comment by mgalloy** [comment]
If this works, we can probably remove a lot of bad cal file epochs.

**Comment by mgalloy** [comment]
We should record the calibration files used in some way:

- a `calibration_files_used.txt` in `process`
- a metadata field in the netCDF calibration file

**Comment by jburkepile** [comment]
Mike:
Looks like your code successfully removed the 3 'bad' calpol files from the 20140102 calibration. These are indeed the only 3 'bad' files that day and these are what you reported above.   Nice job!
   20140102_190331_kcor.fts.gz 
   20140102_190346_kcor.fts.gz 
   20140102_190401_kcor.fts.gz

**Comment by mgalloy** [comment]
There are already "Input File List" and "Input File Type" that list all the calibration files and their type used in the calibration. Need to fix those up.

**Comment by mgalloy** [comment]
Producing cal files from the days with the given epochs removed and the new algorithm filtering files. Results are in `raw.polangle`.

**Comment by mgalloy** [comment]
For some reason, the last three files listed in `Input File List` are repeated, and I think the same is true for `Input File Types`.

**Comment by mgalloy** [comment]
In `raw.polangle`, I confirm that:

- there are 31 total calibration files in `calibration_files.txt`, 3 of them are "calibration" type files with angle 23.85, so there are 28 good calibration files
- in the calibration netCDF file produced for the day, the "Input File Type" and "Input File List" are 28 elements long and exclude the correct 3 bad calibration files
- the end-of-day log for the processing of the day, mentions removing the correct three bad files with bad polarization angles

**Comment by jburkepile** [comment]
I have begun checking the days Mike reprocessed, that remove the bad polarizer angle files from the calibration, beginning with day 20141219:

**20141219** - this day had an 'evil twin' CME; i.e. a CME that had a faint duplicate of itself occurring 45 degrees away due to coronal signal 'leaking' into the background polarization. This was caused by the bad calibration file that contained cross-talk between Stokes I,Q,U states.  **RESULT: The reprocessed 20141219 data looks good. There is no longer an evil-twin CME.**
OLD DATA WITH BAD CAL FILE:
![20141220_004859_kcor_minus_003853_good_badcal](https://github.com/NCAR/kcor-pipeline/assets/18175973/9746d175-034c-4e91-8f7d-27e7c3675ec0)

NEW DATA WITH GOOD CAL IMAGES:
![20141220_004844_kcor_minus_003807_good_goodcal](https://github.com/NCAR/kcor-pipeline/assets/18175973/ecb85ab5-8b65-4964-80b2-5daa59f48e32)

The calibrated pB intensities changed as well. The change was greatest in the inner corona with the most visible change occurring in the south-southeast. This region appeared to have closed field in the bad image. This is gone in the reprocessed data:
OLD pB image with BAD CAL FILE: 
![20141219_175544_badcal_kcor_l2](https://github.com/NCAR/kcor-pipeline/assets/18175973/7a0a3700-a541-4618-bcdd-ada14d07daf4)

NEW pB image with GOOD CAL FILE:
![20141219_175544_goodcal_kcor_l2](https://github.com/NCAR/kcor-pipeline/assets/18175973/2693ff65-f3d6-4766-8fb2-907f2f56407e)

The bad image contained spurious coronal signal from cross-talk. The good image now shows the south-southeast region with no obvious helmet and looking more like a coronal hole. This is now consistent with what is seen by CoMP on this day:
![20141219 comp 1074 daily_enhanced_intensity 3](https://github.com/NCAR/kcor-pipeline/assets/18175973/0290f95a-532a-4864-8bf5-df00d87d39d7)

I need to check more days to ensure all is well, but this is very reassuring.

**Comment by mgalloy** [comment]
The new test dates with bad calibration polarization angle are processed.

**Comment by jburkepile** [comment]
Check that the new calibration files, with the 'bad' angle images removed, do indeed improve the polarization brightness calibrated intensities. To verify that I looked at the plots of azimuthally averaged pB at a fixed height. These plots are made by Mike each day for 4 heights in the corona. On Dec 31, 2014, there was a large data gap in the middle of the day. The processing looks for the calibration file nearest in time to the science images. It turns out that on this day, the data taken early in the day were processed with Dec 30, 2014 cal file, while the data taken late in the day, after the data  gap, were processed with the cal file from Jan 1, 2015. The Dec 30, 2014 cal file contained bad polarization angles. 
The plots below show the change in calibrated pB intensities between the data processed with the 'bad' calibration (Dec 30, 2014) and the data processed with a good cal file (Jan 1, 2015). The pB value at a fixed height should be the same value over a day, unless a large CME occurred and blew out part of the corona on/near the limb. There was a small, faint possible CME this day and it did not impact the pB plots. The plots below show the change in calibrated pB intensities between the data processed with the 'bad' calibration (Dec 30, 2014) and the data processed with a good cal file (Jan 1, 2015). 
![20141231 kcor mean-pb-1 11](https://github.com/NCAR/kcor-pipeline/assets/18175973/8b8780b9-59c4-4d81-9cfd-8177b6aadb6d)

![20141231 kcor mean-pb-1 30](https://github.com/NCAR/kcor-pipeline/assets/18175973/ff09c031-7f0f-4854-b01c-84f94fa61531)

Below are the same plots, but the data taken in the morning were calibraed with the 'corrected' calibration on Dec 30, 2014. Note that the pB values before and after the data gap are now in much better agreement.
![20141231 kcor mean-pb-1 11_with_corrected_cal](https://github.com/NCAR/kcor-pipeline/assets/18175973/83cfd2c1-1909-43ea-b7aa-892397e605f8)

![20141231 kcor mean-pb-1 30_with_corrected_cal](https://github.com/NCAR/kcor-pipeline/assets/18175973/e2ecc61e-132e-42c4-b1ca-a47ca63f19cd)

This strongly suggests that the changes made to the pipeline to remove the 'bad' angle calibration files are working correctly and the pB values are much more accurate and consistent. 
I think it is safe to mark this as closed.
