### ISSUE TITLE
Draw centering info on individual camera images

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#359]
Use 20210703 as test data.

#### Tasks

For quicklooks:

- [x] do not 'fill' the occulter when you draw the circle at the occulter
- [x] change circle drawn around occulter to green
- [x] the '+' sign in the center of occulter is using the array center, but should use the occulter center 

For level 2 UNMASKED GIFS (produced about every 20 minutes):

- [x] draw a circle at the height of the occulter in the color green (do _not_ use the `/FILL` option)

For level 1 unmasked GIFs (produced about every 20 minutes):

- [x] create unmasked GIF per camera with centering annotations at the same cadence as the other unmasked GIFs

#### Questions

- [x] This is done on the realtime quicklooks in the `level0/quicklooks` directory. Is this sufficient or should there be an option to produce annotated level 1 or 2 quicklooks? *No, need specific changes from @jburkepile.*

**Comment by jburkepile** [comment]
For quicklooks:  [NOT the gallery ones for Ben]
-[  ] do not 'fill' the occulter when you draw the circle at the occulter
 -[  ] Change circle drawn around occulter to green
 -[  ]  The '+' sign in the center of occulter is using the array center. 

 For level 2 UNMASKED GIFS (produced about every 20 minutes]
 -[  ] Please draw a circle at the height of the occulter in the color green

**Comment by mgalloy** [comment]
Gallery quicklook:

![20221007_174535_kcor_cam0_gallery_g](https://github.com/NCAR/kcor-pipeline/assets/713524/c41da954-e32a-4b9e-91b4-26d9b80ca5a3)

Normal level 0 quicklook:

![20221007_174535_kcor_cam0_g](https://github.com/NCAR/kcor-pipeline/assets/713524/47693ec1-b121-414e-b7d4-0e2152447c8f)

**Comment by mgalloy** [comment]
@bberkeyU is OK with the same as normal quicklooks.

**Comment by mgalloy** [comment]
Here are the updated level 0 quicklooks:

![20221007_174535_kcor_cam0_gallery_g](https://github.com/NCAR/kcor-pipeline/assets/713524/0429360c-5b37-4b71-8bca-815c55d67dff)

![20221007_174535_kcor_cam0_g](https://github.com/NCAR/kcor-pipeline/assets/713524/17621fb2-7879-4fed-9748-de52c3f1b580)

**Comment by jburkepile** [comment]
Thanks for making these. The data are still masked. You are applying a mask in the quicklook code so it is tough to determine if the green circle is located at the occulter edge. 

To verify the level 1 pipeline centers we could save unmasked 'level1' gifs from each camera with a circle drawn at the occulter, before you shift, rotate and combine the two cameras. That would provide the center found for the calibrated images. We can talk about that to make sure its worth it.
Thanks again!

**Comment by mgalloy** [comment]
Below are the quicklooks without masking. Note that not masking changes the display scaling of the GIF because we take the display maximum from the maximum value in the array. Should we scale according to the max value in the masked version?

![20221007_174535_kcor_cam0_gallery_g](https://github.com/NCAR/kcor-pipeline/assets/713524/fcb2d981-367f-4c56-8b96-d1537f43195c)

![20221007_174535_kcor_cam0_g](https://github.com/NCAR/kcor-pipeline/assets/713524/b65ac5e0-29aa-4a7a-97cf-b04b5405a50f)

**Comment by jburkepile** [comment]
Wow Mike! That was incredibly fast. The unmasked are much better for assessing the accuracy of the occulter size found by the code.  I like your idea to use the masked scaling on the unmasked gif. That's the best of both worlds.

Thanks so much!

**Comment by mgalloy** [comment]
Here is the updated nomask GIF:

![20221007_171731_kcor_l2_nomask](https://github.com/NCAR/kcor-pipeline/assets/713524/7a4472cb-da6e-42c6-a98e-b1d3353c71af)

**Comment by mgalloy** [comment]
Full results are in `raw.latest/20221007`.

**Comment by detoma** [comment]
I am not sure you can use level 2 polarization data to estimate the goodness of the radius. There is too much done to the level2 data. I would go back to Stoke I and do it for the two cameras separately.

**Comment by jburkepile** [comment]
Giuliana: You make a good point. Mike measures the radius in the level 1 pB (after distortion, etc. ) Mike also saves the level 1 intensity image. He can measure the radius of the intensity mage along with the pB image for comparison Thanks very much for pointing that out.

**Comment by mgalloy** [comment]
I have a test run in `raw.latest` for 20240409 with the new level 1 nomask GIFs.

**Comment by mgalloy** [comment]
I was sending the same image into each GIF creation, so getting camera 0 image for both level 1 nomask GIFs.

Also, need to put logic in for making the level 1 nomask GIFs at the same cadence as the regular nomask GIFs, not for every level 1 file.

**Comment by mgalloy** [comment]
The first nomask image (for each camera) is showing green in the saturated areas and annotations, as well as the occulter circle.

- The color table in the GIF is correct. Only color 255 is green.
- The value in the saturated areas of the GIF is 255.
