### ISSUE TITLE
Record and plot image platescale in the end-of-day processing

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#363]
Use the occulter radius size from the routine `kcor_find_image.pro` to compute an image platescale. Record the value of the image platescale in the FITS header keyword `IMAGESCL`. Image platescales will be compared with the original determination of the instrument platescale derived from the K-Cor effective focal length calculated by Dennis Gallagher, and the lab measurements of the K-Cor occulter diameters.

#### Tasks

- [x] `IMAGESCL` keyword
- [x] add `IMAGESCL` keyword to database
- [x] make mission plot of `IMAGESCL` in end-of-day
- [x] add `RCAM_SCL` and `TCAM_SCL` FITS keywords ("distortion corrected image scale for camera {0,1}")
- [x] add `rcam_image_scale` and `tcam_image_scale` `kcor_eng` table fields
- [x] plot each camera separately for mission plot plus a difference plot
- [x] make daily plot of `IMAGESCL` in end-of-day; use different color or symbol for each camera
- [x] annotate RCAM/TCAM in plots
- [x] create CSV file for daily values, columns: filename, `IMAGESCL`, `RCAM_SCL`, `TCAM_SCL`, and `RCAM_SCL` - `TCAM_SCL`
- [x] rolling 90-day image scale plot
- [x] make minor tick marks in n-day plot be 1 day/tickmark

**Comment by mgalloy** [comment]
I have notes about a OC-1018.9" occulter. Was this never used?

**Comment by jburkepile** [comment]
Mike: Thank you for pointing that out. We swapped out the 'old' winter occulter of 1018.9" on Jan 12, 2021 for the new tapered winter occulter. I had forgotten about that. I edited my info above to include both the old and new occulters. Thanks!

**Comment by mgalloy** [comment]
I am running code that calculates `IMAGESCL` on 202210087. I am getting results about 0.034 arcs/pixel less than the current plate scale (5.643 arcsec/pixel).

``` bash
level2$ for f in *_kcor_l2.fts; do echo $f; fitscat -r $f | grep IMAGESCL; done
20221007_171731_kcor_l2.fts
IMAGESCL=               5.6105 / [arcsec/pixel] image scale for this file
20221007_171746_kcor_l2.fts
IMAGESCL=               5.6100 / [arcsec/pixel] image scale for this file
20221007_171801_kcor_l2.fts
IMAGESCL=               5.6098 / [arcsec/pixel] image scale for this file
20221007_171816_kcor_l2.fts
```

**Comment by jburkepile** [comment]
Not surprising. I have been spot-checking days and getting platescles as much as 0.06 arcsec/pix different - always less than the 5.643 arcsec/pix I got back in 2013-early 2014. Using the larger difference of 0.06 arcsec/pixel as a worse case,  we are off by 0.03 solar radii at the outer edge of the field-of-view (the error is much smaller closer to the occulter). That is not awful. The smallest error bar I use for measuring CME positions in the best images is 0.03 solar radii. Many measurements are twice that.

Nevertheless, the platescale is off and needs to be recomputed. I will set up a separate ticket for that. Yesterday, I asked Ben to retrieve 2 of the K-Cor occulters next time he is at MLSO. I want him to mail those back and have the IG measure them again.

It is also possible that a change in distortion correction is playing a role.

So glad you are going to save this info in the headers.

**Comment by mgalloy** [comment]
Here is the mission plot (only 1 day has been processed with `IMAGESCL` values).

![20221007 kcor mission image_scale](https://github.com/NCAR/kcor-pipeline/assets/713524/1bbe34e6-35ac-4d7b-8f3e-41a7ded4f8a5)

**Comment by jburkepile** [comment]
Thanks very much for doing this. Just to clarify the above plot: the red line is the platescale (5.643). Is the black vertical line near the end of the mission the image scale? Are you plotting the distortion corrected occulter radius for each camera separately?

**Comment by mgalloy** [comment]
The black vertical line is comprised of the image scale values for a single day. These image scale values are computed from the average of the two distortion corrected radii. I could store separate `IMAGESCL` values in the FITS header and database, and then produce two image scale plots.

**Comment by mgalloy** [comment]
Here is the daily plot for 2013-11-13:

![20131113 kcor daily image_scale](https://github.com/user-attachments/assets/4b0f9d14-81ca-400a-af29-350bd9fc75a0)

Mission plot is not too valuable until we reprocess:

![20131113 kcor mission image_scale](https://github.com/user-attachments/assets/200b974b-f233-4d3b-b0ed-e13be6550299)

**Comment by mgalloy** [comment]
The CSV file looks like:

```
p$ cat 20131113.kcor.daily.image_scale.csv
2013-11-13 18:52:01, 5.644, 5.649, 5.639, 0.010
2013-11-13 18:52:16, 5.644, 5.649, 5.639, 0.010
2013-11-13 18:52:31, 5.643, 5.649, 5.638, 0.011
2013-11-13 18:52:46, 5.643, 5.648, 5.637, 0.011
2013-11-13 18:53:01, 5.642, 5.647, 5.637, 0.010
2013-11-13 19:01:19, 5.637, 5.642, 5.632, 0.010
2013-11-13 19:01:34, 5.637, 5.642, 5.632, 0.010
2013-11-13 19:37:16, 5.646, 5.652, 5.640, 0.012
2013-11-13 19:37:31, 5.644, 5.649, 5.638, 0.011
2013-11-13 19:37:46, 5.643, 5.649, 5.638, 0.011
2013-11-13 19:38:01, 5.643, 5.649, 5.637, 0.012
2013-11-13 19:38:17, 5.643, 5.649, 5.637, 0.012
2013-11-13 19:38:32, 5.642, 5.648, 5.636, 0.012
...
```

**Comment by mgalloy** [comment]
Updated daily image scale plots:

![20131113 kcor daily image_scale](https://github.com/user-attachments/assets/ba7d6608-eb3e-4df2-8d9f-361af0327b31)

Updated mission image scale plots:

![20131113 kcor mission image_scale](https://github.com/user-attachments/assets/63a523ae-fbc0-4613-ab2a-7fd3db60977b)

**Comment by mgalloy** [comment]
Mission image scale from the 2013 reprocessing:

![20131231 kcor mission image_scale](https://github.com/user-attachments/assets/3bf1b079-0186-4dc5-b681-9a79b503f5e4)

**Comment by mgalloy** [comment]
We will probably want a rolling 90-day plot.

**Comment by mgalloy** [comment]
Here are the mission, rolling 30 day, and rolling 90 day plots for 20131231:

![20131231 kcor mission image_scale](https://github.com/user-attachments/assets/c12a6a23-990b-4101-adfc-adf3520833b7)

![20131231 kcor rolling 30day image_scale](https://github.com/user-attachments/assets/ca4a6c64-56e0-4317-a894-2e556d2719ab)

![20131231 kcor rolling 90day image_scale](https://github.com/user-attachments/assets/4abfd6a7-fed3-4a0a-afb1-4479e7825135)

**Comment by jburkepile** [comment]
Thanks Mike! These are very helpful!
cheers!
joan

**Comment by mgalloy** [comment]
Here are the current plots, with 1 day/minor tickmark for a variety of number of days:

![20131231 kcor rolling 5day image_scale](https://github.com/user-attachments/assets/1c06330f-cd87-4e65-91f9-89f0c79aa372)

![20131231 kcor rolling 10day image_scale](https://github.com/user-attachments/assets/a1cc02f4-31a7-4a11-977a-65aea4bacca2)

![20131231 kcor rolling 20day image_scale](https://github.com/user-attachments/assets/e1e61f18-10a5-404d-8c18-9cf408c5472f)

![20131231 kcor rolling 30day image_scale](https://github.com/user-attachments/assets/469b9bc2-b4e4-4d47-93a6-fb1fbeb0bc7a)

![20131231 kcor rolling 40day image_scale](https://github.com/user-attachments/assets/daf01146-676a-48e5-ad91-1979421dcc48)

![20131231 kcor rolling 50day image_scale](https://github.com/user-attachments/assets/673cf961-a22f-43a0-a757-0252eb8b0e05)

![20131231 kcor rolling 60day image_scale](https://github.com/user-attachments/assets/b048620e-b013-4965-93e2-ec2e6bd69e92)

![20131231 kcor rolling 70day image_scale](https://github.com/user-attachments/assets/580404cb-a0fc-4f78-b25d-7a1e7c8b2fd0)

![20131231 kcor rolling 80day image_scale](https://github.com/user-attachments/assets/da7eb572-76d9-4c85-a25d-aa94f9e0f2b3)

![20131231 kcor rolling 90day image_scale](https://github.com/user-attachments/assets/42d66a9e-aa15-4e9a-8f54-56e942b8e6f3)
