### ISSUE TITLE
First pass reprocessing of early mission

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#365]
Process 20130930 through 20131231.

This is needed to do #211. Then the early mission will need to be processed again.

#### Tasks

- [x] test 20131027 out of production
- [x] test 20131123 out of production
- [x] test 20131101 out of production
- [x] test 20131113 out of production
- [x] test 20131128 out of production
- [x] test 20131210 out of production
- [x] make a release
- [x] produce cals for 20130930-20131231 in production
- [x] reprocess 20130930-20131231 in production
- [x] reprocess 2024 data and check #382

**Comment by mgalloy** [comment]
Test results for 20131027 and 20131123 are in `raw.latest`.

**Comment by jburkepile** [comment]
Thanks Mike! I will take a look and get back to you tomorrow.

**Comment by mgalloy** [comment]
By the way, I was able to make a cal file for the first 6 cal epochs (up to 20131123).

**Comment by jburkepile** [comment]
Mike: Can you send me those dates? There are a number of days in 2013 that do not have valid data due to erroneous info in the fits headers and bad info on location of the calibration hardware in the beam. I need to check that those are good quality calibration data.
Thanks very much!
joan

**Comment by mgalloy** [comment]
20131027 and 20131123 are fully processed. Other days there are just cals.

**Comment by jburkepile** [comment]
I am not sure I understand your last comment. Do you mean that you can't process these days: (see my previous comment that contains the plots).
 Nov 1, 2013
 Nov 13, 2013
 Nov 28, 2013
 Dec 10, 2013
Thanks for clarifying!

**Comment by mgalloy** [comment]
I had not seen your comment adding more days to process. I am processing those now, though I have to get a cal file for cal epoch 7 in order to do the last one.

**Comment by jburkepile** [comment]
Here are the comparisons of Nov 1 and Nov 28 (1 solar rotation apart). The ad hoc camera correction of 2.2 looks okay for these days too:

![KCOR_O~1](https://github.com/user-attachments/assets/0726d879-3bbe-451b-9360-9785714c5e90)

![KCOR_O~2](https://github.com/user-attachments/assets/d48f0f07-bbea-48c9-bddd-dd958e8e6704)

![KCOR_O~3](https://github.com/user-attachments/assets/d3b71f61-1638-4ab5-847f-93c6e3950d2a)

![KCOR_O~4](https://github.com/user-attachments/assets/970e8f74-9536-48aa-be6e-aced9550a034)

**Comment by mgalloy** [comment]
@jburkepile Is that good enough to make a release and reprocess 20130930-20131231 in production?

**Comment by jburkepile** [comment]
Yes!
I have looked at Nov 13 and Dec 10 and they are also a good match. I am working on that figure and will add it later.

Thanks very much!
joan
