### ISSUE TITLE
Change filenames of level 2 pB images and movie

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#366]
The current name of the K-Cor level 2  pB fits files does not identify the data as being polarization brightness. This has been an oversight on my part. I want to add 'pb' to the K-Cor l2 FITS and gif files. 

Please change name K-Cor l2 pB fits filenames from

```
yyyymmdd_hhmmss_kcor_l2.fts.gz
yyyymmdd_hhmmss_kcor_l2.gif
20221025_kcor_l2.mp4
```

to

```
yyyymmdd_hhmmss_kcor_l2_pb.fts.gz
yyyymmdd_hhmmss_kcor_l2_pb.gif
20221025_kcor_l2_pb.mp4
```

Please let me know if you think this change may cause other problems.

#### Questions

- [x] `YYYYMMDD_HHMMSS_kcor_l2_cropped.gif` to `YYYYMMDD_HHMMSS_kcor_l2_pb_cropped.gif`?
- [x] `YYYYMMDD_HHMMSS_kcor_l2_avg.gif` to `YYYYMMDD_HHMMSS_kcor_l2_pb_avg.gif`
- [x] `YYYYMMDD_HHMMSS_kcor_l2_avg_cropped.gif` to `YYYYMMDD_HHMMSS_kcor_l2_pb_avg_cropped.gif`?
- [x] `YYYYMMDD_HHMMSS_kcor_l2_extavg.gif` to `YYYYMMDD_HHMMSS_kcor_l2_pb_extavg.gif`?
- [x] `YYYYMMDD_HHMMSS_kcor_l2_extavg_cropped.gif` to `YYYYMMDD_HHMMSS_kcor_l2_pb_extavg_cropped.gif`?
- [x] `YYYYMMDD_HHMMSS_kcor_l2_avg.fts.gz` to `YYYYMMDD_HHMMSS_kcor_l2_pb_avg.fts.gz`?
- [x] `YYYYMMDD_HHMMSS_kcor_l2_extavg.fts.gz` to `YYYYMMDD_HHMMSS_kcor_l2_pb_extavg.fts.gz`?

#### Tasks

- [x] `yyyymmdd_hhmmss_kcor_l2.fts.gz` to `yyyymmdd_hhmmss_kcor_l2_pb.fts.gz`
- [x] `yyyymmdd_hhmmss_kcor_l2.gif` to `yyyymmdd_hhmmss_kcor_l2_pb.gif`
- [x] `20221025_kcor_l2.mp4` to `20221025_kcor_l2_pb.mp4`
- [x] make frame player on website work

CHANGE to mp4 files:
Want all KCor movies (**except** subtraction movies) to be comprised on 2 min avg images 
Want all movies to have the word 'avg' in the mp4 filename. 

#### Tasks  

1) Use 2 min avg images in mp4 movies (**except s**ubtractions)
- [x] 20160211_kcor_l2_nrgf.mp4   
- [x] 20160211_kcor_l2_nrgf_enhanced.mp4
- [x] 20160211_kcor_l2_pb.mp4
- [x] 20160211_kcor_l2_pb_enhanced.mp4
- [x] 20160211_kcor_l2_nrgf_avg_cropped_enhanced.mp4
- [x] 20160211_kcor_l2_nrgf_cropped.mp4
- [x] 20160211_kcor_l2_pb_avg_cropped_enhanced.mp4
- [x] 20160211_kcor_l2_pb_cropped.mp4

2) Change filename to include the word 'avg'

- [x] Change 20160211_kcor_l2_nrgf.mp4   TO  - 20160211_kcor_l2_nrgf_avg.mp4   
- [x] Change 20160211_kcor_l2_nrgf_enhanced.mp4   TO   20160211_kcor_l2_nrgf_avg_enhanced.mp4
- [x] Change 20160211_kcor_l2_pb.mp4  TO  20160211_kcor_l2_pb_avg.mp4 
- [x] Change 20160211_kcor_l2_pb_enhanced.mp4  TO   0160211_kcor_l2_pb_avg_enhanced.mp4
- [x] 20160211_kcor_l2_nrgf_avg_cropped_enhanced.mp4    ALREADY RENAMED
- [x] Change 20160211_kcor_l2_nrgf_cropped.mp4  TO   20160211_kcor_l2_nrgf_avg_cropped.mp4
- [x] 20160211_kcor_l2_pb_avg_cropped_enhanced.mp4       ALREADY RENAMED
- [x] Change 20160211_kcor_l2_pb_cropped.mp4  TO    20160211_kcor_l2_pb_avg_cropped.mp4

**Comment by mgalloy** [comment]
Test date is 20240409 in `raw.latest`.

**Comment by mgalloy** [comment]
Better day to check is 20221101 in `raw.latest`.

**Comment by mgalloy** [comment]
The website doesn't play the frames of the images, but does allow download of the FITS and GIFs.

**Comment by mgalloy** [comment]
This looks to be fixed on the production website now.

**Comment by mgalloy** [comment]
20240330 and 20240409 are reprocessed in production with these filenames.
