### ISSUE TITLE
Edit epoch.cfg file with more accurate information for 20131122

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#390]
Edit epoch.cfg file for Nov 22, 2013:

- [x] Line 141: Change TODO statement to this comment:  '[20131030] cameras realigned. New distortion test. Unfortunately previous distortion test on Oct 16, prior to alignment, was too out-of-focus to use. The Oct 30 distortion needs to be used for all data going back to Sep 30.
- [x] Line 143: REMOVE. Should be cal epoch 2 and that is already set for this date.
- [x] Line 251 change [20131122]  to [20131122.093243]
- [x] Line 252 change process : NO to process: YES (in fact there are some science data for this epoch on the MLSO web page.
- [x] Line 267: Change epoch time from [20131122.121449] to  [20131122.121624]
- [x] Line 272: Please move and update comment. Put comment between lines 266 and 267 and change  to: _'previous KCor exposures of 0.1, 0.125, and 0.16 ms, were too low to provide enough signal for creation of a camera correction'_
- [x] Lines 272 to 275: You can delete these lines. These data are still 0.16 ms and belong with cal_epoch_version 4. That is already the current epoch.
- [x] Line 278. Change from: [20131122.122403] to [20131122.123347]
- [x] Line 282. Please add this to the comment: data are mostly dark images.
- [x] Add epoch:  comment: Optic, then calibration optic in the beam
                            [20131122.104819]
                            process        : NO
- [x] Add epoch:   [20131122.115432]
                            process          : YES

- [x] Add epoch:   comment: optic in beam or hardware moving? Nothing in observer log.
                            [20131122.130708]
                            process          : NO
- [x] Add epoch:   [20131122.130940]
                            process           : YES

- [x] Add epoch:   comment: comment: Clouds or obstruction in beam. Coronal signal noticeably decreased.
                            [20131122.131328]
                            process            : NO
- [x] Add epoch   [20131122.133849]
                           process             : YES

#### Tasks

- [x] reprocess 20131122 out-of-production

**Comment by mgalloy** [comment]
20131122 has been reprocessed out-of-production and the results are in `raw.latest` in the new location.

**Comment by jburkepile** [comment]
Thanks very much for adding these additional epochs. That removed the bad images with no coronal signal.
