### ISSUE TITLE
New product types in database for enhanced images

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#400]
Enhanced pB and NRGF FITS files need to have their own product type in the database. There should be a database product type for each `PRODUCT` FITS keyword value listed in the table in #312, copied below.

| PRODUCT name | Database name | Database comment |
| -------- | -------- | ---------------- |
| pB | pB | A calibrated polarization brightness  K-Cor image |
| NRGF | nrgf | K-Cor level 1 image with a normalized radially graded filter (nrgf, Morgan et al. 2009, adapted by Silvano Fineschi and Sarah Gibson for KCor use) to maximize image contrast. |
| avg pB | pbavg | Averaged K-Cor level 1 polarized brightness images |
| enh avg pB | pbavgenh | K-Cor enhanced filter applied to averaged K-Cor level 2 pB images |
| ext avg pB | pbextavg | Extended average (nominally 10 minute) K-Cor level 1 polarized brightness images |
| enh ext avg pB | pbextavgenh | K-Cor enhanced filter applied to extended average level 2 pB images |
| avg NRGF | nrgfavg | K-Cor level 1 averaged images with a normalized gradient filter (nrgf) applied |
| ext avg NRGF | nrgfextavg | Extended average (nominally 10 minute) K-Cor level 1 NRGF images |
| enh avg NRGF | nrgfavgenh | K-Cor NRGF applied to enhanced average images |
| enh ext avg NRGF | nrgfextavgenh | K-Cor NRGF applied to enhanced extended average images |

#### Tasks

- [x] add new enhanced products from above table
- [x] make sure each file added to `kcor_img` has the correct `producttype`
- [ ] publish a date in 2013 in production and let Don know for testing

**Comment by mgalloy** [comment]
SQL commands to add new rows:

```
insert into mlso_producttype (producttype, description) values ('pbavgenh', 'Enhanced filter applied to averaged K-Cor level 2 pB images');
insert into mlso_producttype (producttype, description) values ('pbextavgenh', 'Enhanced filter applied to extended average level 2 pB images');
insert into mlso_producttype (producttype, description) values ('nrgfavgenh', 'NRGF applied to enhanced average images');
insert into mlso_producttype (producttype, description) values ('nrgfextavgenh', 'NRGF applied to enhanced extended average images');
```

**Comment by mgalloy** [comment]
``` SQL
select file_name, producttype from kcor_img where obs_day = "10133";
```

yields:

| file_name | producttype |
| --------- | ----------- |
| 20240330_213315_kcor_l2_pb.fts | 1 |
| 20240330_213330_kcor_l2_pb.fts | 1 |
| 20240330_213346_kcor_l2_pb.fts | 1 |
| 20240330_213401_kcor_l2_pb.fts | 1 |
| 20240330_213416_kcor_l2_pb.fts | 1 |
| 20240330_213431_kcor_l2_pb.fts | 1 |
| 20240330_213446_kcor_l2_pb.fts | 1 |
| 20240330_213501_kcor_l2_pb.fts | 1 |
| 20240330_213517_kcor_l2_pb.fts | 1 |
| 20240330_213532_kcor_l2_pb.fts | 1 |
| 20240330_213547_kcor_l2_pb.fts | 1 |
| 20240330_213602_kcor_l2_pb.fts | 1 |
| 20240330_213617_kcor_l2_pb.fts | 1 |
| 20240330_213632_kcor_l2_pb.fts | 1 |
| 20240330_213648_kcor_l2_pb.fts | 1 |
| 20240330_213703_kcor_l2_pb.fts | 1 |
| 20240330_213718_kcor_l2_pb.fts | 1 |
| 20240330_213733_kcor_l2_pb.fts | 1 |
| 20240330_213748_kcor_l2_pb.fts | 1 |
| 20240330_213804_kcor_l2_pb.fts | 1 |
| 20240330_213819_kcor_l2_pb.fts | 1 |
| 20240330_213834_kcor_l2_pb.fts | 1 |
| 20240330_213849_kcor_l2_pb.fts | 1 |
| 20240330_213904_kcor_l2_pb.fts | 1 |
| 20240330_213919_kcor_l2_pb.fts | 1 |
| 20240330_213935_kcor_l2_pb.fts | 1 |
| 20240330_213950_kcor_l2_pb.fts | 1 |
| 20240330_214005_kcor_l2_pb.fts | 1 |
| 20240330_214020_kcor_l2_pb.fts | 1 |
| 20240330_214035_kcor_l2_pb.fts | 1 |
| 20240330_214050_kcor_l2_pb.fts | 1 |
| 20240330_214106_kcor_l2_pb.fts | 1 |
| 20240330_214121_kcor_l2_pb.fts | 1 |
| 20240330_214136_kcor_l2_pb.fts | 1 |
| 20240330_214151_kcor_l2_pb.fts | 1 |
| 20240330_214206_kcor_l2_pb.fts | 1 |
| 20240330_214221_kcor_l2_pb.fts | 1 |
| 20240330_214237_kcor_l2_pb.fts | 1 |
| 20240330_214252_kcor_l2_pb.fts | 1 |
| 20240330_214307_kcor_l2_pb.fts | 1 |
| 20240330_214322_kcor_l2_pb.fts | 1 |
| 20240330_214337_kcor_l2_pb.fts | 1 |
| 20240330_214352_kcor_l2_pb.fts | 1 |
| 20240330_214408_kcor_l2_pb.fts | 1 |
| 20240330_214423_kcor_l2_pb.fts | 1 |
| 20240330_214438_kcor_l2_pb.fts | 1 |
| 20240330_214453_kcor_l2_pb.fts | 1 |
| 20240330_214508_kcor_l2_pb.fts | 1 |
| 20240330_214523_kcor_l2_pb.fts | 1 |
| 20240330_214539_kcor_l2_pb.fts | 1 |
| 20240330_214554_kcor_l2_pb.fts | 1 |
| 20240330_214609_kcor_l2_pb.fts | 1 |
| 20240330_214624_kcor_l2_pb.fts | 1 |
| 20240330_214639_kcor_l2_pb.fts | 1 |
| 20240330_214655_kcor_l2_pb.fts | 1 |
| 20240330_214710_kcor_l2_pb.fts | 1 |
| 20240330_214725_kcor_l2_pb.fts | 1 |
| 20240330_214740_kcor_l2_pb.fts | 1 |
| 20240330_214755_kcor_l2_pb.fts | 1 |
| 20240330_214810_kcor_l2_pb.fts | 1 |
| 20240330_214826_kcor_l2_pb.fts | 1 |
| 20240330_214841_kcor_l2_pb.fts | 1 |
| 20240330_214856_kcor_l2_pb.fts | 1 |
| 20240330_214911_kcor_l2_pb.fts | 1 |
| 20240330_214926_kcor_l2_pb.fts | 1 |
| 20240330_214941_kcor_l2_pb.fts | 1 |
| 20240330_214957_kcor_l2_pb.fts | 1 |
| 20240330_215012_kcor_l2_pb.fts | 1 |
| 20240330_215027_kcor_l2_pb.fts | 1 |
| 20240330_215042_kcor_l2_pb.fts | 1 |
| 20240330_215057_kcor_l2_pb.fts | 1 |
| 20240330_215112_kcor_l2_pb.fts | 1 |
| 20240330_215128_kcor_l2_pb.fts | 1 |
| 20240330_215143_kcor_l2_pb.fts | 1 |
| 20240330_215158_kcor_l2_pb.fts | 1 |
| 20240330_215213_kcor_l2_pb.fts | 1 |
| 20240330_215228_kcor_l2_pb.fts | 1 |
| 20240330_215243_kcor_l2_pb.fts | 1 |
| 20240330_215259_kcor_l2_pb.fts | 1 |
| 20240330_215314_kcor_l2_pb.fts | 1 |
| 20240330_215329_kcor_l2_pb.fts | 1 |
| 20240330_215344_kcor_l2_pb.fts | 1 |
| 20240330_215359_kcor_l2_pb.fts | 1 |
| 20240330_215414_kcor_l2_pb.fts | 1 |
| 20240330_215430_kcor_l2_pb.fts | 1 |
| 20240330_215445_kcor_l2_pb.fts | 1 |
| 20240330_215500_kcor_l2_pb.fts | 1 |
| 20240330_215515_kcor_l2_pb.fts | 1 |
| 20240330_215530_kcor_l2_pb.fts | 1 |
| 20240330_215545_kcor_l2_pb.fts | 1 |
| 20240330_215601_kcor_l2_pb.fts | 1 |
| 20240330_215616_kcor_l2_pb.fts | 1 |
| 20240330_215631_kcor_l2_pb.fts | 1 |
| 20240330_215646_kcor_l2_pb.fts | 1 |
| 20240330_215701_kcor_l2_pb.fts | 1 |
| 20240330_215717_kcor_l2_pb.fts | 1 |
| 20240330_215732_kcor_l2_pb.fts | 1 |
| 20240330_215747_kcor_l2_pb.fts | 1 |
| 20240330_221242_kcor_l2_pb.fts | 1 |
| 20240330_221257_kcor_l2_pb.fts | 1 |
| 20240330_221312_kcor_l2_pb.fts | 1 |
| 20240330_221327_kcor_l2_pb.fts | 1 |
| 20240330_221343_kcor_l2_pb.fts | 1 |
| 20240330_221358_kcor_l2_pb.fts | 1 |
| 20240330_221413_kcor_l2_pb.fts | 1 |
| 20240330_221428_kcor_l2_pb.fts | 1 |
| 20240330_221443_kcor_l2_pb.fts | 1 |
| 20240330_221459_kcor_l2_pb.fts | 1 |
| 20240330_223058_kcor_l2_pb.fts | 1 |
| 20240330_223113_kcor_l2_pb.fts | 1 |
| 20240330_223128_kcor_l2_pb.fts | 1 |
| 20240330_223143_kcor_l2_pb.fts | 1 |
| 20240330_223158_kcor_l2_pb.fts | 1 |
| 20240330_223214_kcor_l2_pb.fts | 1 |
| 20240330_223229_kcor_l2_pb.fts | 1 |
| 20240330_223244_kcor_l2_pb.fts | 1 |
| 20240330_223259_kcor_l2_pb.fts | 1 |
| 20240330_223314_kcor_l2_pb.fts | 1 |
| 20240330_223329_kcor_l2_pb.fts | 1 |
| 20240330_223345_kcor_l2_pb.fts | 1 |
| 20240330_223400_kcor_l2_pb.fts | 1 |
| 20240330_223415_kcor_l2_pb.fts | 1 |
| 20240330_223430_kcor_l2_pb.fts | 1 |
| 20240330_223445_kcor_l2_pb.fts | 1 |
| 20240330_223501_kcor_l2_pb.fts | 1 |
| 20240330_223516_kcor_l2_pb.fts | 1 |
| 20240330_223531_kcor_l2_pb.fts | 1 |
| 20240330_223546_kcor_l2_pb.fts | 1 |
| 20240330_223601_kcor_l2_pb.fts | 1 |
| 20240330_223616_kcor_l2_pb.fts | 1 |
| 20240330_223632_kcor_l2_pb.fts | 1 |
| 20240330_223647_kcor_l2_pb.fts | 1 |
| 20240330_223702_kcor_l2_pb.fts | 1 |
| 20240330_223717_kcor_l2_pb.fts | 1 |
| 20240330_223732_kcor_l2_pb.fts | 1 |
| 20240330_223747_kcor_l2_pb.fts | 1 |
| 20240330_223803_kcor_l2_pb.fts | 1 |
| 20240330_223818_kcor_l2_pb.fts | 1 |
| 20240330_223833_kcor_l2_pb.fts | 1 |
| 20240330_223848_kcor_l2_pb.fts | 1 |
| 20240330_223903_kcor_l2_pb.fts | 1 |
| 20240330_223918_kcor_l2_pb.fts | 1 |
| 20240330_223934_kcor_l2_pb.fts | 1 |
| 20240330_223949_kcor_l2_pb.fts | 1 |
| 20240330_224004_kcor_l2_pb.fts | 1 |
| 20240330_224019_kcor_l2_pb.fts | 1 |
| 20240330_224034_kcor_l2_pb.fts | 1 |
| 20240330_224049_kcor_l2_pb.fts | 1 |
| 20240330_224105_kcor_l2_pb.fts | 1 |
| 20240330_224120_kcor_l2_pb.fts | 1 |
| 20240330_224135_kcor_l2_pb.fts | 1 |
| 20240330_224150_kcor_l2_pb.fts | 1 |
| 20240330_224205_kcor_l2_pb.fts | 1 |
| 20240330_224220_kcor_l2_pb.fts | 1 |
| 20240330_224236_kcor_l2_pb.fts | 1 |
| 20240330_224251_kcor_l2_pb.fts | 1 |
| 20240330_224306_kcor_l2_pb.fts | 1 |
| 20240330_224321_kcor_l2_pb.fts | 1 |
| 20240330_224336_kcor_l2_pb.fts | 1 |
| 20240330_224352_kcor_l2_pb.fts | 1 |
| 20240330_224407_kcor_l2_pb.fts | 1 |
| 20240330_224422_kcor_l2_pb.fts | 1 |
| 20240330_224437_kcor_l2_pb.fts | 1 |
| 20240330_224452_kcor_l2_pb.fts | 1 |
| 20240330_224507_kcor_l2_pb.fts | 1 |
| 20240330_224523_kcor_l2_pb.fts | 1 |
| 20240330_224538_kcor_l2_pb.fts | 1 |
| 20240330_224553_kcor_l2_pb.fts | 1 |
| 20240330_224608_kcor_l2_pb.fts | 1 |
| 20240330_224623_kcor_l2_pb.fts | 1 |
| 20240330_224638_kcor_l2_pb.fts | 1 |
| 20240330_224654_kcor_l2_pb.fts | 1 |
| 20240330_224709_kcor_l2_pb.fts | 1 |
| 20240330_224724_kcor_l2_pb.fts | 1 |
| 20240330_224739_kcor_l2_pb.fts | 1 |
| 20240330_224754_kcor_l2_pb.fts | 1 |
| 20240330_224809_kcor_l2_pb.fts | 1 |
| 20240330_224825_kcor_l2_pb.fts | 1 |
| 20240330_224840_kcor_l2_pb.fts | 1 |
| 20240330_213315_kcor_l2_pb_avg.fts | 5 |
| 20240330_213517_kcor_l2_pb_avg.fts | 5 |
| 20240330_213718_kcor_l2_pb_avg.fts | 5 |
| 20240330_213919_kcor_l2_pb_avg.fts | 5 |
| 20240330_214121_kcor_l2_pb_avg.fts | 5 |
| 20240330_214322_kcor_l2_pb_avg.fts | 5 |
| 20240330_214523_kcor_l2_pb_avg.fts | 5 |
| 20240330_214725_kcor_l2_pb_avg.fts | 5 |
| 20240330_214926_kcor_l2_pb_avg.fts | 5 |
| 20240330_215128_kcor_l2_pb_avg.fts | 5 |
| 20240330_215329_kcor_l2_pb_avg.fts | 5 |
| 20240330_215530_kcor_l2_pb_avg.fts | 5 |
| 20240330_215732_kcor_l2_pb_avg.fts | 5 |
| 20240330_221257_kcor_l2_pb_avg.fts | 5 |
| 20240330_223113_kcor_l2_pb_avg.fts | 5 |
| 20240330_223314_kcor_l2_pb_avg.fts | 5 |
| 20240330_223516_kcor_l2_pb_avg.fts | 5 |
| 20240330_223717_kcor_l2_pb_avg.fts | 5 |
| 20240330_223918_kcor_l2_pb_avg.fts | 5 |
| 20240330_224120_kcor_l2_pb_avg.fts | 5 |
| 20240330_224321_kcor_l2_pb_avg.fts | 5 |
| 20240330_224523_kcor_l2_pb_avg.fts | 5 |
| 20240330_224724_kcor_l2_pb_avg.fts | 5 |
| 20240330_213315_kcor_l2_pb_extavg.fts | 6 |
| 20240330_213315_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_213517_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_213718_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_213919_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_214121_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_214322_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_214523_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_214725_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_214926_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_215128_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_215329_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_215530_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_215732_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_221257_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_223113_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_223314_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_223516_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_223717_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_223918_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_224120_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_224321_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_224523_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_224724_kcor_l2_pb_avg_enhanced.fts | 38 |
| 20240330_213315_kcor_l2_pb_extavg_enhanced.fts | 39 |
| 20240330_213315_kcor_l2_nrgf.fts | 2 |
| 20240330_213315_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_213315_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_213315_kcor_l2_nrgf_extavg.fts | 7 |
| 20240330_213315_kcor_l2_nrgf_extavg_enhanced.fts | 41 |
| 20240330_213330_kcor_l2_nrgf.fts | 2 |
| 20240330_213346_kcor_l2_nrgf.fts | 2 |
| 20240330_213401_kcor_l2_nrgf.fts | 2 |
| 20240330_213416_kcor_l2_nrgf.fts | 2 |
| 20240330_213431_kcor_l2_nrgf.fts | 2 |
| 20240330_213446_kcor_l2_nrgf.fts | 2 |
| 20240330_213501_kcor_l2_nrgf.fts | 2 |
| 20240330_213517_kcor_l2_nrgf.fts | 2 |
| 20240330_213517_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_213517_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_213532_kcor_l2_nrgf.fts | 2 |
| 20240330_213547_kcor_l2_nrgf.fts | 2 |
| 20240330_213602_kcor_l2_nrgf.fts | 2 |
| 20240330_213617_kcor_l2_nrgf.fts | 2 |
| 20240330_213632_kcor_l2_nrgf.fts | 2 |
| 20240330_213648_kcor_l2_nrgf.fts | 2 |
| 20240330_213703_kcor_l2_nrgf.fts | 2 |
| 20240330_213718_kcor_l2_nrgf.fts | 2 |
| 20240330_213718_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_213718_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_213733_kcor_l2_nrgf.fts | 2 |
| 20240330_213748_kcor_l2_nrgf.fts | 2 |
| 20240330_213804_kcor_l2_nrgf.fts | 2 |
| 20240330_213819_kcor_l2_nrgf.fts | 2 |
| 20240330_213834_kcor_l2_nrgf.fts | 2 |
| 20240330_213849_kcor_l2_nrgf.fts | 2 |
| 20240330_213904_kcor_l2_nrgf.fts | 2 |
| 20240330_213919_kcor_l2_nrgf.fts | 2 |
| 20240330_213919_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_213919_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_213935_kcor_l2_nrgf.fts | 2 |
| 20240330_213950_kcor_l2_nrgf.fts | 2 |
| 20240330_214005_kcor_l2_nrgf.fts | 2 |
| 20240330_214020_kcor_l2_nrgf.fts | 2 |
| 20240330_214035_kcor_l2_nrgf.fts | 2 |
| 20240330_214050_kcor_l2_nrgf.fts | 2 |
| 20240330_214106_kcor_l2_nrgf.fts | 2 |
| 20240330_214121_kcor_l2_nrgf.fts | 2 |
| 20240330_214121_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_214121_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_214136_kcor_l2_nrgf.fts | 2 |
| 20240330_214151_kcor_l2_nrgf.fts | 2 |
| 20240330_214206_kcor_l2_nrgf.fts | 2 |
| 20240330_214221_kcor_l2_nrgf.fts | 2 |
| 20240330_214237_kcor_l2_nrgf.fts | 2 |
| 20240330_214252_kcor_l2_nrgf.fts | 2 |
| 20240330_214307_kcor_l2_nrgf.fts | 2 |
| 20240330_214322_kcor_l2_nrgf.fts | 2 |
| 20240330_214322_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_214322_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_214337_kcor_l2_nrgf.fts | 2 |
| 20240330_214352_kcor_l2_nrgf.fts | 2 |
| 20240330_214408_kcor_l2_nrgf.fts | 2 |
| 20240330_214423_kcor_l2_nrgf.fts | 2 |
| 20240330_214438_kcor_l2_nrgf.fts | 2 |
| 20240330_214453_kcor_l2_nrgf.fts | 2 |
| 20240330_214508_kcor_l2_nrgf.fts | 2 |
| 20240330_214523_kcor_l2_nrgf.fts | 2 |
| 20240330_214523_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_214523_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_214539_kcor_l2_nrgf.fts | 2 |
| 20240330_214554_kcor_l2_nrgf.fts | 2 |
| 20240330_214609_kcor_l2_nrgf.fts | 2 |
| 20240330_214624_kcor_l2_nrgf.fts | 2 |
| 20240330_214639_kcor_l2_nrgf.fts | 2 |
| 20240330_214655_kcor_l2_nrgf.fts | 2 |
| 20240330_214710_kcor_l2_nrgf.fts | 2 |
| 20240330_214725_kcor_l2_nrgf.fts | 2 |
| 20240330_214725_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_214725_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_214740_kcor_l2_nrgf.fts | 2 |
| 20240330_214755_kcor_l2_nrgf.fts | 2 |
| 20240330_214810_kcor_l2_nrgf.fts | 2 |
| 20240330_214826_kcor_l2_nrgf.fts | 2 |
| 20240330_214841_kcor_l2_nrgf.fts | 2 |
| 20240330_214856_kcor_l2_nrgf.fts | 2 |
| 20240330_214911_kcor_l2_nrgf.fts | 2 |
| 20240330_214926_kcor_l2_nrgf.fts | 2 |
| 20240330_214926_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_214926_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_214941_kcor_l2_nrgf.fts | 2 |
| 20240330_214957_kcor_l2_nrgf.fts | 2 |
| 20240330_215012_kcor_l2_nrgf.fts | 2 |
| 20240330_215027_kcor_l2_nrgf.fts | 2 |
| 20240330_215042_kcor_l2_nrgf.fts | 2 |
| 20240330_215057_kcor_l2_nrgf.fts | 2 |
| 20240330_215112_kcor_l2_nrgf.fts | 2 |
| 20240330_215128_kcor_l2_nrgf.fts | 2 |
| 20240330_215128_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_215128_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_215143_kcor_l2_nrgf.fts | 2 |
| 20240330_215158_kcor_l2_nrgf.fts | 2 |
| 20240330_215213_kcor_l2_nrgf.fts | 2 |
| 20240330_215228_kcor_l2_nrgf.fts | 2 |
| 20240330_215243_kcor_l2_nrgf.fts | 2 |
| 20240330_215259_kcor_l2_nrgf.fts | 2 |
| 20240330_215314_kcor_l2_nrgf.fts | 2 |
| 20240330_215329_kcor_l2_nrgf.fts | 2 |
| 20240330_215329_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_215329_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_215344_kcor_l2_nrgf.fts | 2 |
| 20240330_215359_kcor_l2_nrgf.fts | 2 |
| 20240330_215414_kcor_l2_nrgf.fts | 2 |
| 20240330_215430_kcor_l2_nrgf.fts | 2 |
| 20240330_215445_kcor_l2_nrgf.fts | 2 |
| 20240330_215500_kcor_l2_nrgf.fts | 2 |
| 20240330_215515_kcor_l2_nrgf.fts | 2 |
| 20240330_215530_kcor_l2_nrgf.fts | 2 |
| 20240330_215530_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_215530_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_215545_kcor_l2_nrgf.fts | 2 |
| 20240330_215601_kcor_l2_nrgf.fts | 2 |
| 20240330_215616_kcor_l2_nrgf.fts | 2 |
| 20240330_215631_kcor_l2_nrgf.fts | 2 |
| 20240330_215646_kcor_l2_nrgf.fts | 2 |
| 20240330_215701_kcor_l2_nrgf.fts | 2 |
| 20240330_215717_kcor_l2_nrgf.fts | 2 |
| 20240330_215732_kcor_l2_nrgf.fts | 2 |
| 20240330_215732_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_215732_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_215747_kcor_l2_nrgf.fts | 2 |
| 20240330_221257_kcor_l2_nrgf.fts | 2 |
| 20240330_221257_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_221257_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_221312_kcor_l2_nrgf.fts | 2 |
| 20240330_221327_kcor_l2_nrgf.fts | 2 |
| 20240330_221343_kcor_l2_nrgf.fts | 2 |
| 20240330_221358_kcor_l2_nrgf.fts | 2 |
| 20240330_221413_kcor_l2_nrgf.fts | 2 |
| 20240330_221428_kcor_l2_nrgf.fts | 2 |
| 20240330_221443_kcor_l2_nrgf.fts | 2 |
| 20240330_221459_kcor_l2_nrgf.fts | 2 |
| 20240330_223113_kcor_l2_nrgf.fts | 2 |
| 20240330_223113_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_223113_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_223128_kcor_l2_nrgf.fts | 2 |
| 20240330_223143_kcor_l2_nrgf.fts | 2 |
| 20240330_223158_kcor_l2_nrgf.fts | 2 |
| 20240330_223214_kcor_l2_nrgf.fts | 2 |
| 20240330_223229_kcor_l2_nrgf.fts | 2 |
| 20240330_223244_kcor_l2_nrgf.fts | 2 |
| 20240330_223259_kcor_l2_nrgf.fts | 2 |
| 20240330_223314_kcor_l2_nrgf.fts | 2 |
| 20240330_223314_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_223314_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_223329_kcor_l2_nrgf.fts | 2 |
| 20240330_223345_kcor_l2_nrgf.fts | 2 |
| 20240330_223400_kcor_l2_nrgf.fts | 2 |
| 20240330_223415_kcor_l2_nrgf.fts | 2 |
| 20240330_223430_kcor_l2_nrgf.fts | 2 |
| 20240330_223445_kcor_l2_nrgf.fts | 2 |
| 20240330_223501_kcor_l2_nrgf.fts | 2 |
| 20240330_223516_kcor_l2_nrgf.fts | 2 |
| 20240330_223516_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_223516_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_223531_kcor_l2_nrgf.fts | 2 |
| 20240330_223546_kcor_l2_nrgf.fts | 2 |
| 20240330_223601_kcor_l2_nrgf.fts | 2 |
| 20240330_223616_kcor_l2_nrgf.fts | 2 |
| 20240330_223632_kcor_l2_nrgf.fts | 2 |
| 20240330_223647_kcor_l2_nrgf.fts | 2 |
| 20240330_223702_kcor_l2_nrgf.fts | 2 |
| 20240330_223717_kcor_l2_nrgf.fts | 2 |
| 20240330_223717_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_223717_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_223732_kcor_l2_nrgf.fts | 2 |
| 20240330_223747_kcor_l2_nrgf.fts | 2 |
| 20240330_223803_kcor_l2_nrgf.fts | 2 |
| 20240330_223818_kcor_l2_nrgf.fts | 2 |
| 20240330_223833_kcor_l2_nrgf.fts | 2 |
| 20240330_223848_kcor_l2_nrgf.fts | 2 |
| 20240330_223903_kcor_l2_nrgf.fts | 2 |
| 20240330_223918_kcor_l2_nrgf.fts | 2 |
| 20240330_223918_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_223918_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_223934_kcor_l2_nrgf.fts | 2 |
| 20240330_223949_kcor_l2_nrgf.fts | 2 |
| 20240330_224004_kcor_l2_nrgf.fts | 2 |
| 20240330_224019_kcor_l2_nrgf.fts | 2 |
| 20240330_224034_kcor_l2_nrgf.fts | 2 |
| 20240330_224049_kcor_l2_nrgf.fts | 2 |
| 20240330_224105_kcor_l2_nrgf.fts | 2 |
| 20240330_224120_kcor_l2_nrgf.fts | 2 |
| 20240330_224120_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_224120_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_224135_kcor_l2_nrgf.fts | 2 |
| 20240330_224150_kcor_l2_nrgf.fts | 2 |
| 20240330_224205_kcor_l2_nrgf.fts | 2 |
| 20240330_224220_kcor_l2_nrgf.fts | 2 |
| 20240330_224236_kcor_l2_nrgf.fts | 2 |
| 20240330_224251_kcor_l2_nrgf.fts | 2 |
| 20240330_224306_kcor_l2_nrgf.fts | 2 |
| 20240330_224321_kcor_l2_nrgf.fts | 2 |
| 20240330_224321_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_224321_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_224336_kcor_l2_nrgf.fts | 2 |
| 20240330_224352_kcor_l2_nrgf.fts | 2 |
| 20240330_224407_kcor_l2_nrgf.fts | 2 |
| 20240330_224422_kcor_l2_nrgf.fts | 2 |
| 20240330_224437_kcor_l2_nrgf.fts | 2 |
| 20240330_224452_kcor_l2_nrgf.fts | 2 |
| 20240330_224507_kcor_l2_nrgf.fts | 2 |
| 20240330_224523_kcor_l2_nrgf.fts | 2 |
| 20240330_224523_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_224523_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_224538_kcor_l2_nrgf.fts | 2 |
| 20240330_224553_kcor_l2_nrgf.fts | 2 |
| 20240330_224608_kcor_l2_nrgf.fts | 2 |
| 20240330_224623_kcor_l2_nrgf.fts | 2 |
| 20240330_224638_kcor_l2_nrgf.fts | 2 |
| 20240330_224654_kcor_l2_nrgf.fts | 2 |
| 20240330_224709_kcor_l2_nrgf.fts | 2 |
| 20240330_224724_kcor_l2_nrgf.fts | 2 |
| 20240330_224724_kcor_l2_nrgf_avg.fts | 4 |
| 20240330_224724_kcor_l2_nrgf_avg_enhanced.fts | 40 |
| 20240330_224739_kcor_l2_nrgf.fts | 2 |
| 20240330_224754_kcor_l2_nrgf.fts | 2 |
| 20240330_224809_kcor_l2_nrgf.fts | 2 |
| 20240330_224825_kcor_l2_nrgf.fts | 2 |
| 20240330_224840_kcor_l2_nrgf.fts | 2 |
