### ISSUE TITLE
Retrieve KCor level 0 data from glade for reprocessing

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#403]
Some of the KCor level 0 data were removed from the MLSO servers due to lack of space. The level 0 data needs to be retrieved for these years:

#### Tasks

 - [x] retrieve 2015 - NOTE processing directory was on mlsodata3 and is now on `/hao/aimdata/mlsodata-BAK/mlsodata3` 
 - [x] retrieve 2016 - NOTE processing directory was on mlsodata2 and is now on `/hao/aimdata/mlsodata-BAK/mlsodata2` 
 - [x] retrieve 2017 - processing directories on `/hao/sunrise`
 - [x] retrieve 2018 - processing directories on `/hao/mahidata1`
 - [x] unpack 2015
 - [x] unpack 2016
 - [x] unpack 2017
 - [x] unpack 2018

**Comment by mgalloy** [comment]
For 2017, there is only 694G available in its current location. There is about 3.5T of level 0, 6.5T of level 1, and 3.5T of level 2 data stored at the current MLSO server. There are 292 days with data in 2017 on Campaign Storage, containing a total of about 5.5T of level 0 data (3.3 of level 1 and 1.8T of level 2), all in compressed tarballs. At the compression levels of level 1 and 2 data, there should be about 11.0T of level 0 data, so we need to download, and find a place to store, 7.5T of level 0 data for 2017.

**Comment by mgalloy** [comment]
For 2018, there is about 3.7T of level 0, 2.0 TB of level 1, and 1.1TB of level 2 data on Campaign Storage. There are 12.0T available on the MLSO server holding 2018 data.

**Comment by mgalloy** [comment]
For 2015, there are 4.9T of level 0 data on Campaign Storage. On the MLSO server, there are 2.3T of level 0. So 2 * 4.9T - 2.3T = 7.5T extra to be stored.

For 2016, there are 5.4T of level 0 data on Campaign Storage. On the MLSO server, there are 2.9T of level0. So 2 * 5.4T - 2.9T = 7.9T extra to be stored.

Fortunately, there is 42T free on the MLSO server that stores these data. Transfers have been initiated via Globus.

**Comment by jburkepile** [comment]
As you know, the new level 2 data will take up some additional space since we are making 30 sec subtraction images, and 2 min enhanced pB and nrgf images.

**Comment by mgalloy** [comment]
Yes, and the 2x factor is probably a poor estimate as well, but the locations I am moving forward with have plenty of extra space. The 2017 data is the only one we need to think about.

**Comment by jburkepile** [comment]
Perfect! Thanks so much
