### ISSUE TITLE
Add additional fields to database for plate scale calculation

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#407]
Add additional fields to `kcor_eng` for plate scale calculation:

- `rcam_dcr`
- `tcam_dcr`

#### Questions

- [x] How to compute distance to zenith? Can I just use `mlso_secant_z`? Should I put this in the FITS header as well? From `mlso_secant_z`: `hour_angle`, `sec_z`, `sidereal_time`, `sol_dec`, `sol_ra`, `dist`

#### Tasks

- [x] add fields to `kcor_eng_create_table.pl`
- [x] add fields to existing dev and prod databases
- [x] update fields in `kcor_eng_insert.pro`
- [x] add distortion-corrected x- and y-coordinates
- [x] add distance to zenith
- [x] add MLSO lat/lon to mission table

**Comment by bberkeyU** [comment]
There are a few FITS keywords that dont get captured in the database.  I dont think they should all be captured, but I tried to group the values where I think they should go if we do capture them.

Hardware information should be in kcor_hw/kcor_cal
LYOTSTOP= 'in      '           / specifies if the 2nd Lyot stop is in the beam  

Observer: Not sure if needed, maybe kcor_raw
OBSERVER= 'Waters  '           / name of Mauna Loa observer                     

Image alignment data potentially include in kcor_eng
XCAMCSH0=                    2 / [px] cam corr shift to align w/ img, + to left  
XCAMCSH1=                    2 / [px] cam corr shift to align w/ img, + to left  
XCAMSH0 =                    0 / [px] image shift, + to right                    
XCAMSH1 =                    0 / [px] image shift, + to right                    
TCAM_DCX=               513.19 / [pixel] camera 1 dist cor occulter X center    
TCAM_DCY=               512.80 / [pixel] camera 1 dist cor occulter Y center    
RCAM_DCY=               512.73 / [pixel] camera 0 dist cor occulter Y center    
RCAM_DCX=               513.09 / [pixel] camera 0 dist cor occulter X center    

Image/Plate scale information:  kcor_eng
CDELT1  =               5.6430 / [arcsec/pixel] solar X increment = platescale  
CDELT2  =               5.6430 / [arcsec/pixel] solar Y increment = platescale  
CRLN_OBS=               86.008 / [deg] solar L angle: Carrington longitude      
CRLT_OBS=                4.503 / [deg] solar B angle: Carrington latitude       
CRPIX1  =               512.50 / [pixel] solar X center (index origin=1)        
CRPIX2  =               512.50 / [pixel] solar Y center (index origin=1)        
CRVAL1  =                 0.00 / [arcsec] solar Y sun center                    
CTYPE1  = 'HPLN-TAN'           / [deg] helioprojective west angle: solar X      
CTYPE2  = 'HPLT-TAN'           / [deg] helioprojective north angle: solar Y     
CUNIT1  = 'arcsec  '           / unit of CRVAL1                                 
CUNIT2  = 'arcsec  '           / unit of CRVAL2                                 
CRVAL2  =                 0. 

Processing inputs:    kcor_sci
SKYTRANS=                1.006 / sky transmission correction normalized to gain 
CAMERAS = 'both    '           / cameras used in processing                    
ROLLCORR=                  0.7 / [deg] clockwise offset: spar polar axis align. 
DMODSWID= '2016-05-26'         / date of demodulation software                  
SKYPOLRM= 'subtraction'        / sky polarization removal method                 


Calibration inputs: kcor_cal
TCAMPOLS=                    0 / first state used in polarization demodulation  
RCAMPOLS=                    0 / first state used in polarization demodulation  
BIASCORR=                    0 / bias added after sky polarization correction    
CALFILE = '20171030_192142_kcor_cal_v13_2.0.65_2.500ms.ncdf' / calibration file 

Camera fixes:  kcor_raw
FIXCAMLC=                    1 / interp over bad pixels in camera lin correction
TCAMCORR= 'camera_calibration_MV-D1024E-CL-13890_02.5000_lut13890-20160716.ncdf'
RCAMCORR= 'camera_calibration_MV-D1024E-CL-13891_02.5000_lut13891-20160716.ncdf'

WCS data:  Maybe kcor_sci
SOLARDEC=              -14.026 / [deg] solar declination                        
SOLAR_RA=              215.187 / [h] solar right ascension (hours)              
SOLAR_P0=               24.659 / [deg] solar P angle applied (image has N up)   
RSUN_REF=          6.96182E+08 / [m] solar radius doi:10.1051/0004-6361/20173215
RSUN    =               966.49 / [arcsec] solar radius (old standard keyword)   
R_SUN   =               171.27 / [pixel] solar radius                         
HGLT_OBS=                4.503 / [deg] Stonyhurst heliographic latitude         
HGLN_OBS=                0.000 / [deg] Stonyhurst heliographic longitude          
DSUN_OBS=       148535499453.4 / [m] distance to the Sun from observer          


Capture more sgs data?
SGS not SGSDIMS,SGSDIMSV

**Comment by mgalloy** [comment]
Adding the new columns to the `kcor_eng` table:

``` mysql
alter table kcor_eng add column hour_angle float after obs_day;
alter table kcor_eng add column sec_z float after hour_angle;
alter table kcor_eng add column sidereal_time float after sec_z;
alter table kcor_eng add column sol_dec float after sidereal_time;
alter table kcor_eng add column sol_ra float after sol_dec;
alter table kcor_eng add column dist_au float after sol_ra;
```

**Comment by mgalloy** [comment]
Adding new distortion corrected x- and y-coordinates:

``` sql
alter table kcor_eng add column rcam_dcx float(9, 3) after tcam_rad;
alter table kcor_eng add column rcam_dcy float(9, 3) after rcam_dcx;
alter table kcor_eng add column tcam_dcx float(9, 3) after rcam_dcy;
alter table kcor_eng add column tcam_dcy float(9, 3) after tcam_dcx;
```

**Comment by mgalloy** [comment]
MLSO lat/lon coordinates:

```
lat =    19.535506
lon = - 155.576587
```

SQL to add the columns:

``` SQL
alter table kcor_mission add column latitude double after location;
alter table kcor_mission add column longitude double after latitude;
```

and populate them:

``` SQL
update kcor_mission set latitude=19.535506, longitude=-155.576587 where mission_id=1;
```

**Comment by mgalloy** [comment]
Here are the first 10 rows of the new columns in `kcor_eng` in the dev database for 20240409:

| eng_id | file_name | hour_angle | sec_z | sidereal_time | sol_dec | sol_ra | dist_au | rcam_dcx | rcam_dcy | tcam_dcx | tcam_dcy | rcam_dcr | tcam_dcr |
| ------ | --------- | ---------- | ----- | ------------- | ------- | ------ | ------- | -------- | -------- | -------- | -------- | -------- | -------- |
| 5881896 | 20240409_174852_kcor_l2_pb.fts | -1.16847 | 2.42854 | 0.298457 | 7.95875 | 18.8161 | 1.00177 | 512.900 | 513.490 | 514.830 | 515.030 | 180.180 | 180.340 |
| 5881897 | 20240409_174907_kcor_l2_pb.fts | -1.16737 | 2.42303 | 0.298631 | 7.95882 | 18.8163 | 1.00177 | 512.920 | 513.460 | 514.840 | 515.020 | 180.230 | 180.380 |
| 5881898 | 20240409_174922_kcor_l2_pb.fts | -1.16628 | 2.41754 | 0.298805 | 7.95888 | 18.8165 | 1.00177 | 512.910 | 513.450 | 514.830 | 514.970 | 180.240 | 180.390 |
| 5881899 | 20240409_174937_kcor_l2_pb.fts | -1.16519 | 2.41209 | 0.298979 | 7.95895 | 18.8166 | 1.00177 | 512.930 | 513.410 | 514.840 | 514.970 | 180.290 | 180.400 |
| 5881900 | 20240409_174953_kcor_l2_pb.fts | -1.16403 | 2.40629 | 0.299165 | 7.95901 | 18.8168 | 1.00177 | 512.930 | 513.370 | 514.870 | 514.960 | 180.340 | 180.430 |
| 5881901 | 20240409_175008_kcor_l2_pb.fts | -1.16294 | 2.40089 | 0.299339 | 7.95908 | 18.8169 | 1.00177 | 512.920 | 513.390 | 514.870 | 514.960 | 180.320 | 180.440 |
| 5881902 | 20240409_175023_kcor_l2_pb.fts | -1.16185 | 2.39551 | 0.299513 | 7.95914 | 18.8171 | 1.00177 | 512.930 | 513.390 | 514.840 | 514.960 | 180.350 | 180.450 |
| 5881903 | 20240409_175038_kcor_l2_pb.fts | -1.16076 | 2.39016 | 0.299687 | 7.95921 | 18.8173 | 1.00177 | 512.930 | 513.400 | 514.850 | 514.960 | 180.360 | 180.460 |
| 5881904 | 20240409_175053_kcor_l2_pb.fts | -1.15966 | 2.38484 | 0.299862 | 7.95927 | 18.8174 | 1.00177 | 512.920 | 513.410 | 514.850 | 514.960 | 180.330 | 180.460 |

**Comment by jburkepile** [comment]
Mike:
I suggest adding mlso to the location keywords for longitude and latitude:
MLSOlong
MLSOlat

what do you think?

**Comment by mgalloy** [comment]
What if the location of K-Cor changes? Ideally, wouldn't K-Cor move to the COSMO location?

**Comment by jburkepile** [comment]
I gotta credit you for thinking decades ahead. 
Please add something in the comment:  
/ Physical Latitude of Mauna Loa Solar Observatory    
and   / Physical Longitude of Mauna Loa Solar Observatory
This defines where KCor has been since 2013. The comment can change if/when it moves.
Thanks Mike!

**Comment by mgalloy** [comment]
There are no comments for fields in the database. There is a `location` field with value "Mauna Loa Solar Observatory".

| mission_id | date | mlso_url | doi_url | telescope | instrument | location | latitude | longitude | origin | object | wavelength | wavefwhm | cdelt | fov_min | fov_max | bitpix | xdim | ydim | wcsname | ctype | timesys | inst_rot | cam0_modstate1 | cam0_modstate2 | cam0_modstate3 | cam0_modstate4 | cam1_modstate1 | cam1_modstate2 | cam1_modstate3 | cam1_modstate4 | pc1_1 | pc1_2 | pc2_1 | pc2_2 | waveunit |
| ---------- | ---- | -------- | ------- | --------- | ---------- | -------- | -------- | --------- | ------ | ------ | ---------- | -------- | ----- | ------- | ------- | ------ | ---- | ---- | ------- | ----- | ------- | -------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- | ----- | ----- | ----- | ----- | -------- |
| 1 | "2013-09-30 18:43:01" | www2.hao.ucar.edu/mlso/m | http://ezid.cdlib.org/id/doi:10.5065/D69G5JV8 | "COSMO K-Coronagraph" | "COSMO K-Coronagraph" | "Mauna Loa Solar Observatory" | 19.535506 | -155.576587 | NCAR/HAO | "Polarization Brightness K-Corona" | 735.00 | 30.00 | 5.643 | 1.05 | 3.00 | 16 | 1024 | 1024 | helioprojective-cartesian | HPLN-TAN | UTC | 0.00 | "half plus" | high | low | "half minus" | "half minus" | low | high | "half plus" | 1.000 | 0.000 | 0.000 | 1.000 | nm |
