### ISSUE TITLE
Radius metrics to compare to standard distortion corrected radii

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#412]
There are 2 radii that would be useful to compare to the standard distortion corrected radii, `{R,T}CAM_DCR`:

- the radius of the distortion corrected flats
- the radius of the unflat-corrected, distortion corrected intensity

#### Questions

- [x] It seems like we should not use `/CENTER_GUESS` in the `KCOR_FIND_IMAGE` calls on the flats. Should we use them on the science images? *Yes, there is a gradient in the science images so `/CENTER_GUESS` can be used, but not in the flats.*

#### Tasks

- [x] report 3 radii in the realtime log in one line
- [x] in cal netCDF: store distortion corrected average gain, center info of raw average gain, and center info of distortion-corrected average gain
- [x] in `kcor_cal` database: store center info of raw individual flats and center info of distortion-corrected individual flats

#### Summary

Use `/CENTER_GUESS` only on science images because it requires a gradient from the occulter outward. Flats do not have this gradient.

**Comment by mgalloy** [comment]
Here are the radii by the 3 difference methods for 20170531:

- "sci": our normal distortion corrected radius as reported in `{R,T}CAM_DCR`
- "dc gain": distortion corrected gain
- "dc ungain for sci": a distortion corrected, but not gain corrected science image

Here are the first 4 science files:

```
RCAM radii sci: 180.56, dc gain: 181.44, dc ungain cor sci: 180.59
TCAM radii sci: 180.14, dc gain: 180.79, dc ungain cor sci: 180.14
RCAM radii sci: 180.57, dc gain: 181.44, dc ungain cor sci: 180.56
TCAM radii sci: 180.16, dc gain: 180.79, dc ungain cor sci: 180.16
RCAM radii sci: 180.58, dc gain: 181.44, dc ungain cor sci: 180.57
TCAM radii sci: 180.16, dc gain: 180.79, dc ungain cor sci: 180.16
RCAM radii sci: 180.57, dc gain: 181.44, dc ungain cor sci: 180.58
TCAM radii sci: 180.17, dc gain: 180.79, dc ungain cor sci: 180.17
```

[Full results.](https://github.com/user-attachments/files/17634809/radii-by-3-methods.txt)

**Comment by bberkeyU** [comment]
Is the correct understanding of this that the occulter radii as seen in the FLATS is larger than what we see in the SCIENCE files? [0.8arcseconds in RCAM and 0.4 arcseconds in TCAM]?  And basically identical between flat correct and flat uncorrected science files?

Do we have a good explanation about why the flats are bigger? Is this diffraction of the disk light around the occutler apparently shrinking its radii? If so what does the flat radii give the "correct" result?

**Comment by mgalloy** [comment]
I agree with this:

> Is the correct understanding of this that the occulter radii as seen in the FLATS is larger than what we see in the SCIENCE files? [0.8arcseconds in RCAM and 0.4 arcseconds in TCAM]? And basically identical between flat correct and flat uncorrected science files?

I'm not sure of the explanation. Eliminating the easy stuff: the cal file used, and hence the flats used, for flat fielding are from the same day, so the occulter for everything is OC-1006.9". We are comparing apples to apples.

**Comment by mgalloy** [comment]
@bberkeyU made some comments and a plot via email that I didn't want to lose:

> I have plotted Mikes's table for RCAM/TCAM and the 3 flavors of measurement vs time.  It shouldn't be surprising that the flat-only value is constant for the whole day since it was based on one image. But we can see the radii change over the observing day for the other two calculations, NORMAL and SCI, without flat.

![image](https://github.com/user-attachments/assets/4cae5839-5b6e-40dc-8e5d-1fa5fe44a84f)

"One Does Not Simply" meme omitted.

**Comment by mgalloy** [comment]
Here is the layout of the cal files now:

``` IDL
IDL> f = '20240330_215832_kcor_cal_v26_2.1.26-dev_2.500ms.ncdf'      
IDL> mg_nc_dump, f                                                   
+ FILE <20240330_215832_kcor_cal_v26_2.1.26-dev_2.500ms.ncdf>
  . ATTRIBUTE strarr(1) title
  . ATTRIBUTE strarr(1) epoch_version
  . ATTRIBUTE strarr(1) flat-date-obs
  . ATTRIBUTE strarr(1) version
  - VARIABLE strarr(30) Input File List
  - VARIABLE strarr(30) Input File Type
  - VARIABLE fltarr(1024, 1024, 2) Dark
  - VARIABLE fltarr(1024, 1024, 2) Distortion-Corrected Gain
    . ATTRIBUTE dblarr(1) RCAM x-center
    . ATTRIBUTE dblarr(1) RCAM y-center
    . ATTRIBUTE dblarr(1) RCAM radius
    . ATTRIBUTE dblarr(1) TCAM x-center
    . ATTRIBUTE dblarr(1) TCAM y-center
    . ATTRIBUTE dblarr(1) TCAM radius
  - VARIABLE fltarr(1024, 1024, 2) Gain
    . ATTRIBUTE dblarr(1) RCAM x-center
    . ATTRIBUTE dblarr(1) RCAM y-center
    . ATTRIBUTE dblarr(1) RCAM radius
    . ATTRIBUTE dblarr(1) TCAM x-center
    . ATTRIBUTE dblarr(1) TCAM y-center
    . ATTRIBUTE dblarr(1) TCAM radius
  - VARIABLE fltarr(1) DIM Reference Voltage
    . ATTRIBUTE strarr(1) units
  - VARIABLE fltarr(1) DIM Reference Voltage Standard Deviation
  - VARIABLE lonarr(1) numsum
  - VARIABLE fltarr(1) exptime
  - VARIABLE intarr(2, 50000) Pixels Fit with Model for Beam 0
  - VARIABLE fltarr(17, 50000) Model Fit Parameters for Beam 0
  - VARIABLE fltarr(17, 50000) Model Fit Parameters Formal Errors for Beam 0
  - VARIABLE intarr(2, 50000) Pixels Fit with Model for Beam 1
  - VARIABLE fltarr(17, 50000) Model Fit Parameters for Beam 1
  - VARIABLE fltarr(17, 50000) Model Fit Parameters Formal Errors for Beam 1
  - VARIABLE fltarr(1024, 1024, 2, 3, 4) Modulation Matrix
  - VARIABLE fltarr(1024, 1024, 2, 4, 3) Demodulation Matrix
  - VARIABLE strarr(1) lyotstop
  - VARIABLE lonarr(1) NPick
```

To retrieve one of the centering info attributes:

``` IDL
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
       181.57370
```

**Comment by mgalloy** [comment]
For 20170531, I am now reporting the flat/gain radii in various ways:

- In the `KCOR_L1`, using the gain the way it is applied to the science images:

  ```
  2024-12-10 20:35:36 DEBUG: KCOR_L1: RCAM radii dc gain: 178.16
  2024-12-10 20:35:36 DEBUG: KCOR_L1: TCAM radii dc gain: 180.79
  ```

- Individual flats, in the database or the logs when creating the database centering info:

```
  MariaDB [MLSO]> select file_name, rcam_radius, tcam_radius, rcam_dc_radius, tcam_dc_radius from kcor_cal where obs_day=7552 and diffuser='in' and calpol='out';
  +--------------------------+-------------+-------------+----------------+----------------+
  | file_name                | rcam_radius | tcam_radius | rcam_dc_radius | tcam_dc_radius |
  +--------------------------+-------------+-------------+----------------+----------------+
  | 20170531_182824_kcor.fts |     178.077 |     180.512 |        181.431 |         181.11 |
  | 20170531_182839_kcor.fts |     178.056 |     180.492 |        181.409 |        181.089 |
  +--------------------------+-------------+-------------+----------------+--------------—+
  ```

- In the average flats:

``` IDL
  IDL> print, mg_nc_getdata(f, 'Gain.RCAM radius')
         179.05554
  IDL> print, mg_nc_getdata(f, 'Gain.TCAM radius')
         179.15917
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
         177.08865
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
         177.72198
  ```

**Comment by mgalloy** [comment]
After fixing a bug in the code of finding the centering info for TCAM in the netCDF cal file, I now get:

``` IDL
IDL> print, mg_nc_getdata(f, 'Gain.RCAM radius')
       179.05554
IDL> print, mg_nc_getdata(f, 'Gain.TCAM radius')
       178.35738
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
       177.08865
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
       181.12295
```

The distortion-corrected TCAM now is fairly close to the individual flat FITS file values which also agree with @jburkepile's analysis.

**Comment by mgalloy** [comment]
I removed the `rcam_gain = reverse(rcam_gain, 2)` and now the distortion-corrected RCAM gain radius is the same as the individual flats in the "kcor_cal" table:

``` IDL
IDL> print, mg_nc_getdata(f, 'Gain.RCAM radius')
       179.15917
IDL> print, mg_nc_getdata(f, 'Gain.TCAM radius')
       178.35738
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
       181.41152
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
       181.12295
```

I have no idea why this is.

**Comment by mgalloy** [comment]
The center finding seems sensitive to the optional parameters of `KCOR_FIND_IMAGE`. I removed everything except the gain image and radius guess when I find the centering info in `KCOR_REDUCE_CALIBRATION_WRTIE`:

``` IDL
  center_info = kcor_find_image(gain, $
                                radius_guess, $
                                ; /center_guess, $
                                ; xoffset=center_offset[0], $
                                ; yoffset=center_offset[1], $
                                ; max_center_difference=run->epoch('max_center_difference'), $
                                log_name='kcor/eod')
```

And now I get:

``` IDL
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
       181.45136
IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
       181.12295
```

This agrees exactly with the results of @jburkepile's script finding the centering info from the netCDF cal file.

**Comment by mgalloy** [comment]
Preliminary testing on 20240330 seems like this is the issue.

- In `KCOR_L1`:

  ```
  2024-12-12 14:44:12 DEBUG: KCOR_L1: RCAM radii dc gain: 182.67
  2024-12-12 14:44:12 DEBUG: KCOR_L1: TCAM radii dc gain: 182.77
  ```

- In individual flats:

  ```
  MariaDB [MLSO]> select file_name, rcam_radius, tcam_radius, rcam_dc_radius, tcam_dc_radius from kcor_cal where obs_day=10133 and diffuser='in' and calpol='out';
  +--------------------------+-------------+-------------+----------------+----------------+
  | file_name                | rcam_radius | tcam_radius | rcam_dc_radius | tcam_dc_radius |
  +--------------------------+-------------+-------------+----------------+----------------+
  | 20240330_220003_kcor.fts |     180.267 |     183.248 |        182.698 |        182.771 |
  | 20240330_220019_kcor.fts |     180.227 |     183.206 |        182.664 |        182.729 |
  | 20240330_220034_kcor.fts |     180.177 |     183.168 |        182.626 |        182.691 |
  +--------------------------+-------------+-------------+----------------+----------------+
  3 rows in set (0.002 sec)
  ```

- In the averaged gain in the netCDF cal file:

  ``` IDL
  IDL> f = '20240330_215832_kcor_cal_v26_2.1.26-dev_2.500ms.ncdf'
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
         182.69962
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
         182.76550
  ```

This is consistent across the use of the flats/gains. Running on 20170531 now. If this holds for the test date, then I think we have the how to handle the flats. Right now, these options are used to find the center in the science images. Is that right?

**Comment by mgalloy** [comment]
20170531 results without `/CENTER_GUESS`:

- In `KCOR_L1`:

  ```
  2024-12-12 18:59:10 DEBUG: KCOR_L1: RCAM radii dc gain: 181.46
  2024-12-12 18:59:10 DEBUG: KCOR_L1: TCAM radii dc gain: 181.14
  ```

- Individual flats:

  ```
  MariaDB [MLSO]> select file_name, rcam_radius, tcam_radius, rcam_dc_radius, tcam_dc_radius from kcor_cal where obs_day=7552 and diffuser='in' and calpol='out';
  +--------------------------+-------------+-------------+----------------+----------------+
  | file_name                | rcam_radius | tcam_radius | rcam_dc_radius | tcam_dc_radius |
  +--------------------------+-------------+-------------+----------------+----------------+
  | 20170531_182824_kcor.fts |     179.115 |     181.461 |        181.431 |         181.11 |
  | 20170531_182839_kcor.fts |     179.094 |      181.44 |        181.409 |        181.089 |
  +--------------------------+-------------+-------------+----------------+----------------+
  2 rows in set (0.001 sec)
  ```

- In the averaged gain in the netCDF cal file:

  ``` IDL
  IDL> f = '20170531_182638_kcor_cal_v13_2.1.26-dev_2.500ms.ncdf'
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.RCAM radius')
         181.45136
  IDL> print, mg_nc_getdata(f, 'Distortion-Corrected Gain.TCAM radius')
         181.12295
  ```

These are consistent about +/- 0.05 between the different methods and about +/-0.03 between cameras.

**Comment by mgalloy** [comment]
I have added a question to this issue: It seems like we should not use `/CENTER_GUESS` in the KCOR_FIND_IMAGE calls on the flats. Should we use them on the science images?

**Comment by bberkeyU** [comment]
What should center guess do?  I was kind of surprised both cameras user the same guess, not camera/epoch based.

**Comment by jburkepile** [comment]
We want to improve the guess by using different values for each occulter. The current guess of 178 pixels can work for the summer occulter ( 991 arcsec) but is too low for the other occulters. We can use Samaiyah's plots at the BOTTOM of ticket 367 to come up with new guesses for each occulter.

**Comment by jburkepile** [comment]
Mike - are the occulter raw center locations for the images currently stored in the database? We also need to know how the center guess impacts the center result to determine the importance of a good center guess. 
If the raw center guess produces a significantly better result (i.e. we need a good center guess) AND if that info is in the database, they can be extracted to provide epoch-driven center guesses per camera for the reprocessing.

**Comment by mgalloy** [comment]
We can easily make the center guess based on the occulter.

We currently find centering info on raw data for testing our methods, but will we need to do that accurately in production? Can raw data just use the 178 pixel default?

**Comment by detoma** [comment]
The center guess is important. My recollection is that for some images it did not find the correct center/radius without a center guess. If KCor is always very close to the center of the detector then you do not need a center guess, but I doubt it is always the case. 

The problem is that if you start too far from the center, you may not find the right the inflection points as they can be outside of the dr range used or too close to the edge of dr. On the other side, If you make dr too large, you have different failures. So the right combination is to use a dr that is not too large and a center guess that is fairly close to the real center.

Things to do are:
- compare results with center_guess on and off
- take a look at the center guess routine and improve it as needed

For the radius guess we should use a different number for each occulter, as Joan suggested. This is what we deduced to do for COMP.

**Comment by mgalloy** [comment]
What do you mean by "the raw center locations"? For science images that are not distortion-corrected?

Currently, what is stored in the database:

- raw science image centers and radii
- distortion-corrected science image radii (but recently added, so we only have values for a few days)
- raw and distortion-corrected centers and radii for all flats (but recently added, so we only have values for a few days)
