### ISSUE TITLE
Add [XY]OFFSET for finding image center

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#90]
It would be useful to add an x- and y-offset to images for specific runs for days where a more precise centering is known.

#### Tasks

- [x] specify x-offset and y-offset via configuration file and make available in `kcor_run` object
- [x] add `[XY]OFFSET` keywords (with default 0.0) to `KCOR_FIND_IMAGE`
- [x] add `[XY]OFFSET` to *some* calls of `KCOR_FIND_IMAGE` (need help from @detoma for this one)
- [x] add `[XY]OFFSET` to L1.5 header if not `0.0`

**Comment by mgalloy** [comment]
`kcor_find_image` is used in:

- `kcor_plotcenters`
- `kcor_plotraw`
- `kcor_quality`
- `kcor_l1`
- `kcor_nrgf`
- `kcor_rg2m`

**Comment by mgalloy** [comment]
359962a6730127dadd34fc28c4f3168688789f01 uses `center_offset`
